00000 : A9 AA                          LDA   #$AA                         [    IMMEDIATE ]
00002 : 20 EF FF                       JSR   $FFEF                        [     ABSOLUTE ]
00005 : A9 8D                          LDA   #$8D                         [    IMMEDIATE ]
00007 : 20 EF FF                       JSR   $FFEF                        [     ABSOLUTE ]
0000A : A0 FF                          LDY   #$FF                         [    IMMEDIATE ]
0000C : C8                             INY                                [     IMPLICIT ]
0000D : AD 11 D0                       LDA   $D011                        [     ABSOLUTE ]
00010 : 10 FB                          BPL   *FB [-5]                     [     RELATIVE ]
00012 : AD 10 D0                       LDA   $D010                        [     ABSOLUTE ]
00015 : 99 00 02                       STA   $0200,Y                      [   ABSOLUTE_Y ]
00018 : 20 EF FF                       JSR   $FFEF                        [     ABSOLUTE ]
0001B : C9 9B                          CMP   #$9B                         [    IMMEDIATE ]
0001D : F0 E1                          BEQ   *E1 [-31]                    [     RELATIVE ]
0001F : C9 8D                          CMP   #$8D                         [    IMMEDIATE ]
00021 : D0 E9                          BNE   *E9 [-23]                    [     RELATIVE ]
00023 : A2 FF                          LDX   #$FF                         [    IMMEDIATE ]
00025 : A9 00                          LDA   #$00                         [    IMMEDIATE ]
00027 : 85 24                          STA   $24                          [     ZEROPAGE ]
00029 : 85 25                          STA   $25                          [     ZEROPAGE ]
0002B : 85 26                          STA   $26                          [     ZEROPAGE ]
0002D : 85 27                          STA   $27                          [     ZEROPAGE ]
0002F : E8                             INX                                [     IMPLICIT ]
00030 : BD 00 02                       LDA   $0200,X                      [   ABSOLUTE_X ]
00033 : C9 D2                          CMP   #$D2                         [    IMMEDIATE ]
00035 : F0 56                          BEQ   *56 [86]                     [     RELATIVE ]
00037 : C9 D7                          CMP   #$D7                         [    IMMEDIATE ]
00039 : F0 35                          BEQ   *35 [53]                     [     RELATIVE ]
0003B : C9 AE                          CMP   #$AE                         [    IMMEDIATE ]
0003D : F0 27                          BEQ   *27 [39]                     [     RELATIVE ]
0003F : C9 8D                          CMP   #$8D                         [    IMMEDIATE ]
00041 : F0 20                          BEQ   *20 [32]                     [     RELATIVE ]
00043 : C9 A0                          CMP   #$A0                         [    IMMEDIATE ]
00045 : F0 E8                          BEQ   *E8 [-24]                    [     RELATIVE ]
00047 : 49 B0                          EOR   #$B0                         [    IMMEDIATE ]
00049 : C9 0A                          CMP   #$0A                         [    IMMEDIATE ]
0004B : 90 06                          BCC   *06 [6]                      [     RELATIVE ]
0004D : 69 88                          ADC   #$88                         [    IMMEDIATE ]
0004F : C9 FA                          CMP   #$FA                         [    IMMEDIATE ]
00051 : 90 AD                          BCC   *AD [-83]                    [     RELATIVE ]
00053 : 0A                             ASL   A                            [  ACCUMULATOR ]
00054 : 0A                             ASL   A                            [  ACCUMULATOR ]
00055 : 0A                             ASL   A                            [  ACCUMULATOR ]
00056 : 0A                             ASL   A                            [  ACCUMULATOR ]
00057 : A0 04                          LDY   #$04                         [    IMMEDIATE ]
00059 : 0A                             ASL   A                            [  ACCUMULATOR ]
0005A : 26 24                          ROL   $24                          [     ZEROPAGE ]
0005C : 26 25                          ROL   $25                          [     ZEROPAGE ]
0005E : 88                             DEY                                [     IMPLICIT ]
0005F : D0 F8                          BNE   *F8 [-8]                     [     RELATIVE ]
00061 : F0 CC                          BEQ   *CC [-52]                    [     RELATIVE ]
00063 : 4C 1A FF                       JMP   $FF1A                        [     ABSOLUTE ]
00066 : A5 24                          LDA   $24                          [     ZEROPAGE ]
00068 : 85 26                          STA   $26                          [     ZEROPAGE ]
0006A : A5 25                          LDA   $25                          [     ZEROPAGE ]
0006C : 85 27                          STA   $27                          [     ZEROPAGE ]
0006E : B0 BF                          BCS   *BF [-65]                    [     RELATIVE ]
00070 : A9 40                          LDA   #$40                         [    IMMEDIATE ]
00072 : 20 CC C1                       JSR   $C1CC                        [     ABSOLUTE ]
00075 : 88                             DEY                                [     IMPLICIT ]
00076 : A2 00                          LDX   #$00                         [    IMMEDIATE ]
00078 : A1 26                          LDA   ($26, X)                     [   INDIRECT_X ]
0007A : A2 10                          LDX   #$10                         [    IMMEDIATE ]
0007C : 0A                             ASL   A                            [  ACCUMULATOR ]
0007D : 20 DB C1                       JSR   $C1DB                        [     ABSOLUTE ]
00080 : D0 FA                          BNE   *FA [-6]                     [     RELATIVE ]
00082 : 20 F1 C1                       JSR   $C1F1                        [     ABSOLUTE ]
00085 : A0 1E                          LDY   #$1E                         [    IMMEDIATE ]
00087 : 90 EC                          BCC   *EC [-20]                    [     RELATIVE ]
00089 : A6 28                          LDX   $28                          [     ZEROPAGE ]
0008B : B0 98                          BCS   *98 [-104]                   [     RELATIVE ]
0008D : 20 BC C1                       JSR   $C1BC                        [     ABSOLUTE ]
00090 : A9 16                          LDA   #$16                         [    IMMEDIATE ]
00092 : 20 CC C1                       JSR   $C1CC                        [     ABSOLUTE ]
00095 : 20 BC C1                       JSR   $C1BC                        [     ABSOLUTE ]
00098 : A0 1F                          LDY   #$1F                         [    IMMEDIATE ]
0009A : 20 BF C1                       JSR   $C1BF                        [     ABSOLUTE ]
0009D : B0 F9                          BCS   *F9 [-7]                     [     RELATIVE ]
0009F : 20 BF C1                       JSR   $C1BF                        [     ABSOLUTE ]
000A2 : A0 3A                          LDY   #$3A                         [    IMMEDIATE ]
000A4 : A2 08                          LDX   #$08                         [    IMMEDIATE ]
000A6 : 48                             PHA                                [     IMPLICIT ]
000A7 : 20 BC C1                       JSR   $C1BC                        [     ABSOLUTE ]
000AA : 68                             PLA                                [     IMPLICIT ]
000AB : 2A                             ROL   A                            [  ACCUMULATOR ]
000AC : A0 39                          LDY   #$39                         [    IMMEDIATE ]
000AE : CA                             DEX                                [     IMPLICIT ]
000AF : D0 F5                          BNE   *F5 [-11]                    [     RELATIVE ]
000B1 : 81 26                          STA   ($26, X)                     [   INDIRECT_X ]
000B3 : 20 F1 C1                       JSR   $C1F1                        [     ABSOLUTE ]
000B6 : A0 35                          LDY   #$35                         [    IMMEDIATE ]
000B8 : 90 EA                          BCC   *EA [-22]                    [     RELATIVE ]
000BA : B0 CD                          BCS   *CD [-51]                    [     RELATIVE ]
000BC : 20 BF C1                       JSR   $C1BF                        [     ABSOLUTE ]
000BF : 88                             DEY                                [     IMPLICIT ]
000C0 : AD 81 C0                       LDA   $C081                        [     ABSOLUTE ]
000C3 : C5 29                          CMP   $29                          [     ZEROPAGE ]
000C5 : F0 F8                          BEQ   *F8 [-8]                     [     RELATIVE ]
000C7 : 85 29                          STA   $29                          [     ZEROPAGE ]
000C9 : C0 80                          CPY   #$80                         [    IMMEDIATE ]
000CB : 60                             RTS                                [     IMPLICIT ]
000CC : 86 28                          STX   $28                          [     ZEROPAGE ]
000CE : A0 42                          LDY   #$42                         [    IMMEDIATE ]
000D0 : 20 E0 C1                       JSR   $C1E0                        [     ABSOLUTE ]
000D3 : D0 F9                          BNE   *F9 [-7]                     [     RELATIVE ]
000D5 : 69 FE                          ADC   #$FE                         [    IMMEDIATE ]
000D7 : B0 F5                          BCS   *F5 [-11]                    [     RELATIVE ]
000D9 : A0 1E                          LDY   #$1E                         [    IMMEDIATE ]
000DB : 20 E0 C1                       JSR   $C1E0                        [     ABSOLUTE ]
000DE : A0 2C                          LDY   #$2C                         [    IMMEDIATE ]
000E0 : 88                             DEY                                [     IMPLICIT ]
000E1 : D0 FD                          BNE   *FD [-3]                     [     RELATIVE ]
000E3 : 90 05                          BCC   *05 [5]                      [     RELATIVE ]
000E5 : A0 2F                          LDY   #$2F                         [    IMMEDIATE ]
000E7 : 88                             DEY                                [     IMPLICIT ]
000E8 : D0 FD                          BNE   *FD [-3]                     [     RELATIVE ]
000EA : BC 00 C0                       LDY   $C000,X                      [   ABSOLUTE_X ]
000ED : A0 29                          LDY   #$29                         [    IMMEDIATE ]
000EF : CA                             DEX                                [     IMPLICIT ]
000F0 : 60                             RTS                                [     IMPLICIT ]
000F1 : A5 26                          LDA   $26                          [     ZEROPAGE ]
000F3 : C5 24                          CMP   $24                          [     ZEROPAGE ]
000F5 : A5 27                          LDA   $27                          [     ZEROPAGE ]
000F7 : E5 25                          SBC   $25                          [     ZEROPAGE ]
000F9 : E6 26                          INC   $26                          [     ZEROPAGE ]
000FB : D0 02                          BNE   *02 [2]                      [     RELATIVE ]
000FD : E6 27                          INC   $27                          [     ZEROPAGE ]
000FF : 60                             RTS                                [     IMPLICIT ]
